[package]
name = "rustify"
version = "0.1.0"
authors = ["HiveMac"]

[lib]
name = "rustify"

[dependencies]
reqwest = "0.1.0"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8.18"
log = "0.3.6"
ansi_term = "0.9.0"